// src/validators/xbrlValidators.js
// GENERATED by scripts/sync-validators.js — do not edit by hand.
// Source: xbrl-quiz-app/src/utils/validators.js (22 validators)
/* eslint-disable */
const { DOMParser, XPathResult } = require('./domShim');
// The browser source has debug console.log calls that dump whole DOM trees;
// silence just console.log inside this module (warn/error still go out).
const console = { ...globalThis.console, log() {} };

// src/utils/validators.js

function validateUnitRefAnswer(userInput) {
  const match = userInput.match(/unitRef\s*=\s*"([^"]+)"/i);
  if (!match) {
    return {
      isCorrect: false,
      error: "❌ No unitRef attribute found in your answer.",
    };
  }
  const unitRef = match[1].trim();
  if (unitRef.toLowerCase() !== "u1") {
    return {
      isCorrect: false,
      error: `❌ unitRef="${unitRef}" should be exactly "u1".`,
    };
  }
  return { isCorrect: true };
}

function validateContextRefAnswer(userInput) {
  const match = userInput.match(/contextRef\s*=\s*"([^"]+)"/i);
  if (!match) {
    return {
      isCorrect: false,
      error: "❌ No contextRef attribute found in your answer.",
    };
  }
  const contextRef = match[1].trim();
  if (contextRef !== "C1") {
    return {
      isCorrect: false,
      error: `❌ contextRef="${contextRef}" must exactly match "C1" (case-sensitive).`,
    };
  }
  return { isCorrect: true };
}

function validateDateRangeAnswer(userInput) {
  const startMatch = userInput.match(/<xbrli:startDate>(.*?)<\/xbrli:startDate>/);
  const endMatch = userInput.match(/<xbrli:endDate>(.*?)<\/xbrli:endDate>/);

  if (!startMatch || !endMatch) {
    return {
      isCorrect: false,
      error: "❌ Missing <xbrli:startDate> or <xbrli:endDate> element.",
    };
  }

  const startDate = new Date(startMatch[1]);
  const endDate = new Date(endMatch[1]);

  // Check if dates parsed correctly
  if (isNaN(startDate.getTime())) {
    return {
      isCorrect: false,
      error: "❌ <xbrli:startDate> is not a valid date.",
    };
  }

  if (isNaN(endDate.getTime())) {
    return {
      isCorrect: false,
      error: "❌ <xbrli:endDate> is not a valid date.",
    };
  }

  // Check if startDate < endDate
  if (startDate >= endDate) {
    return {
      isCorrect: false,
      error: "❌ startDate must be before endDate.",
    };
  }

  return { isCorrect: true };
}

function validateCurrencyCodeAnswer(userInput) {
  const validCodes = ["USD", "EUR", "INR", "JPY"];
  const match = userInput.match(/<xbrli:measure>(.*?)<\/xbrli:measure>/);
  if (!match) {
    return {
      isCorrect: false,
      error: "❌ No <xbrli:measure> element found.",
    };
  }
  const code = match[1].replace(/^iso4217:/, "").toUpperCase();
  if (!validCodes.includes(code)) {
    return {
      isCorrect: false,
      error: `❌ Currency code "${code}" is invalid. Use one of: ${validCodes.join(", ")}.`,
    };
  }
  return { isCorrect: true };
}

function validateRevenueValueAnswer(userInput) {
  const match = userInput.match(/>(-?\d+)<\//); // capture numeric value inside tag
  if (!match) {
    return {
      isCorrect: false,
      error: "❌ Could not find numeric value of Revenue.",
    };
  }
  const value = Number(match[1]);
  if (isNaN(value)) {
    return {
      isCorrect: false,
      error: "❌ Revenue value is not a valid number.",
    };
  }
  if (value < 0) {
    return {
      isCorrect: false,
      error: "❌ Revenue value must be greater than or equal to zero.",
    };
  }
  return { isCorrect: true };
}

// utils/validators.js

/**
 * Validates all 3 fixes in the XBRL snippet:
 * - startDate < endDate
 * - currency code is valid ISO4217
 * - Revenue value >= 0
 *
 * @param {string} inputXml - User-submitted XML snippet as string
 * @returns {object} - { isCorrect: boolean, error: string|null }
 */
function validateAllFixesAnswer(inputXml) {
  // Helper regex and parsing
  const startDateMatch = inputXml.match(/<xbrli:startDate>(.*?)<\/xbrli:startDate>/);
  const endDateMatch = inputXml.match(/<xbrli:endDate>(.*?)<\/xbrli:endDate>/);
  const measureMatch = inputXml.match(/<xbrli:measure>(.*?)<\/xbrli:measure>/);
  const revenueValueMatch = inputXml.match(/<ex:Revenue[^>]*>(-?\d+)<\/ex:Revenue>/);

  // Validate dates
  if (!startDateMatch || !endDateMatch) {
    return { isCorrect: false, error: "❌ Missing startDate or endDate element." };
  }
  const startDate = new Date(startDateMatch[1]);
  const endDate = new Date(endDateMatch[1]);
  if (!(startDate instanceof Date && !isNaN(startDate)) || !(endDate instanceof Date && !isNaN(endDate))) {
    return { isCorrect: false, error: "❌ Invalid date format in startDate or endDate." };
  }
  if (startDate >= endDate) {
    return { isCorrect: false, error: "❌ startDate must be before endDate." };
  }

  // Validate currency measure
  if (!measureMatch) {
    return { isCorrect: false, error: "❌ Missing measure element." };
  }
  const validCurrencies = ["USD", "EUR", "INR", "JPY"];
  // Remove 'iso4217:' prefix if present
  const currencyCode = measureMatch[1].replace(/^iso4217:/i, "").toUpperCase();
  if (!validCurrencies.includes(currencyCode)) {
    return { isCorrect: false, error: `❌ Invalid currency code "${currencyCode}". Must be one of: ${validCurrencies.join(", ")}.` };
  }

  // Validate revenue value
  if (!revenueValueMatch) {
    return { isCorrect: false, error: "❌ Missing revenue value." };
  }
  const revenue = parseInt(revenueValueMatch[1], 10);
  if (isNaN(revenue)) {
    return { isCorrect: false, error: "❌ Revenue value is not a valid number." };
  }
  if (revenue < 0) {
    return { isCorrect: false, error: "❌ Revenue must be greater than or equal to zero." };
  }

  // If all validations pass
  return { isCorrect: true, error: null };
}

// utils/validators.js

function validateBushchatHandsOnSnippet(xml) {
  // 1. Date validity (should be valid date, e.g. 2024-12-01)
  const instantMatch = xml.match(/<xbrli:instant>(.*?)<\/xbrli:instant>/);
  if (!instantMatch) {
    return { isCorrect: false, error: "❌ Missing <xbrli:instant> element." };
  }
  const instantDate = new Date(instantMatch[1]);
  if (isNaN(instantDate.getTime())) {
    return { isCorrect: false, error: "❌ <xbrli:instant> is not a valid date." };
  }

  // 2. Currency code must be all caps
  const measureMatch = xml.match(/<xbrli:measure>(.*?)<\/xbrli:measure>/);
  if (!measureMatch) {
    return { isCorrect: false, error: "❌ Missing <xbrli:measure> element." };
  }
  if (!/^iso4217:[A-Z]{3}$/.test(measureMatch[1])) {
    return { isCorrect: false, error: "❌ Currency code must be upper-case ISO 4217 (e.g. USD, EUR)." };
  }

  // 3. Decimals: should be "INF" or a valid integer
  // For extra realism, prefer integer matching decimal places in value
  const assetsMatch = xml.match(/<ex:Assets[^>]*decimals="([^"]+)"[^>]*>([\d\.,]+)<\/ex:Assets>/);
  if (!assetsMatch) {
    return { isCorrect: false, error: "❌ <ex:Assets> element (with decimals) not found." };
  }
  const decimalsValue = assetsMatch[1];
  if (decimalsValue !== "INF" && isNaN(Number(decimalsValue))) {
    return { isCorrect: false, error: "❌ decimals should be an integer (e.g. 2 for 1000000.50) or INF." };
  }
  // Optional: check if decimals matches value
  const valueParts = assetsMatch[2].split(".");
  if ((valueParts.length === 2) && decimalsValue !== "INF" && valueParts[1].length !== parseInt(decimalsValue, 10)) {
    return { isCorrect: false, error: `❌ The decimals attribute should match the number of digits after the decimal point in the amount (${valueParts[1].length}).` };
  }

  // 4. No contextRef should reference undefined context IDs
  // Find all context id's
  const contextIds = Array.from(xml.matchAll(/<xbrli:context id="([^"]+)"/g)).map(m => m[1]);
  // Find all contextRef attributes
  const contextRefs = Array.from(xml.matchAll(/contextRef="([^"]+)"/g)).map(m => m[1]);
  for (const ref of contextRefs) {
    if (!contextIds.includes(ref)) {
      return { isCorrect: false, error: `❌ contextRef "${ref}" does not refer to any defined context.` };
    }
  }

  // All checks passed!
  return { isCorrect: true, error: null };
}

// utils/validators.js

/**
 * Validates explicit dimension usage inside the context segment.
 * Checks:
 * - The context has a <xbrli:segment> with <xbrldi:explicitMember>
 * - The explicitMember has dimension="ex:RegionAxis"
 * - The member is "ex:AsiaMember"
 *
 * Note: This is a syntactic check; full taxonomy validation requires external data.
 *
 * @param {string} inputXml
 * @returns {{isCorrect:boolean,error:string|null}}
 */
function validateDimensionUsage(inputXml) {
  const contextSegmentMatch = inputXml.match(/<xbrli:context[^>]*id="C1"[^>]*>([\s\S]*?)<\/xbrli:context>/i);
  if (!contextSegmentMatch) {
    return { isCorrect: false, error: "❌ Missing context with id='C1'." };
  }
  const contextContent = contextSegmentMatch[1];

  // Check for <xbrli:segment> existence
  if (!/<xbrli:segment>/.test(contextContent) || !/<\/xbrli:segment>/.test(contextContent)) {
    return { isCorrect: false, error: "❌ Context 'C1' must include a <xbrli:segment> element." };
  }

  // Extract explicitMember inside segment
  const explicitMemberMatch = contextContent.match(/<xbrldi:explicitMember\s+dimension="([^"]+)">([^<]+)<\/xbrldi:explicitMember>/i);
  if (!explicitMemberMatch) {
    return { isCorrect: false, error: "❌ Missing <xbrldi:explicitMember> inside the segment with dimension attribute." };
  }

  const dimension = explicitMemberMatch[1];
  const member = explicitMemberMatch[2];

  if (dimension !== "ex:RegionAxis") {
    return { isCorrect: false, error: `❌ The dimension attribute should be "ex:RegionAxis", found "${dimension}".` };
  }
  if (member !== "ex:AsiaMember") {
    return { isCorrect: false, error: `❌ The explicitMember value should be "ex:AsiaMember", found "${member}".` };
  }

  // If all checks passed:
  return { isCorrect: true, error: null };
}

/**
 * Validates calculation of financial facts:
 * - Sum of Revenue + OtherIncome equals TotalIncome (all for the same contextRef and unitRef)
 * Returns an error if mismatch or missing values.
 *
 * @param {string} inputXml
 * @returns {{isCorrect:boolean,error:string|null}}
 */
function validateCalculation(inputXml) {
  // Helper to extract numeric fact value by concept name, contextRef, unitRef
  function extractFactValue(concept) {
    const regex = new RegExp(`<${concept}[^>]*contextRef="([^"]+)"[^>]*unitRef="([^"]+)"[^>]*decimals="[^"]*"[^>]*>([\\d.,-]+)<\\/${concept}>`, 'i');
    const match = inputXml.match(regex);
    if (!match) return null;
    const valueStr = match[3].replace(/,/g, ''); // Remove possible commas
    const val = parseFloat(valueStr);
    return Number.isNaN(val) ? null : val;
  }

  const revenue = extractFactValue("ex:Revenue");
  const otherIncome = extractFactValue("ex:OtherIncome");
  const totalIncome = extractFactValue("ex:TotalIncome");

  if (revenue === null) return { isCorrect: false, error: "❌ Missing or invalid <ex:Revenue> fact." };
  if (otherIncome === null) return { isCorrect: false, error: "❌ Missing or invalid <ex:OtherIncome> fact." };
  if (totalIncome === null) return { isCorrect: false, error: "❌ Missing or invalid <ex:TotalIncome> fact." };

  const sum = revenue + otherIncome;

  // Compare with small tolerance due to floats if decimals were allowed
  if (Math.abs(sum - totalIncome) > 0.0001) {
    return { isCorrect: false, error: `❌ Calculation error: Revenue (${revenue}) + OtherIncome (${otherIncome}) != TotalIncome (${totalIncome}).` };
  }

  return { isCorrect: true, error: null };
}

/**
 * Comprehensive validation:
 * - Runs dimension usage check
 * - Runs calculation check
 * - Validates decimals and currency code consistency
 *
 * @param {string} inputXml
 * @returns {{isCorrect:boolean,error:string|null}}
 */
function validateDimensionAndCalculation(inputXml) {
  // 1. Dimension check
  const dimResult = validateDimensionUsage(inputXml);
  if (!dimResult.isCorrect) return dimResult;

  // 2. Calculation check
  const calcResult = validateCalculation(inputXml);
  if (!calcResult.isCorrect) return calcResult;

  // 3. Decimals & currency validation
  // Check decimals attributes are integer strings for all facts
  const decimalsMatches = [...inputXml.matchAll(/decimals="([^"]+)"/g)];
  for (const match of decimalsMatches) {
    const val = match[1];
    if (!/^(INF|[+-]?\d+)$/.test(val)) {
      return { isCorrect: false, error: `❌ Invalid decimals value "${val}". Must be integer or "INF".` };
    }
  }

  // Check currency code in unit is valid and uppercase
  const measureMatch = inputXml.match(/<xbrli:measure>(iso4217:[A-Z]{3})<\/xbrli:measure>/i);
  if (!measureMatch) {
    return { isCorrect: false, error: "❌ Missing or invalid <xbrli:measure> with ISO4217 currency code." };
  }
  // Note: optionally validate the code against a list of allowed currencies here

  return { isCorrect: true, error: null };
}

// export function validateBeginner1(userAnswer) {
//   try {
//     // Regex to find the xbrldi:explicitMember within xbrli:segment
//     // It's designed to be somewhat flexible with whitespace and attribute order.
//     //
//     // Group 1: dimension attribute value
//     // Group 2: member text content
//     const regex = /<xbrli:segment>\s*<xbrldi:explicitMember\s+dimension="([^"]+)">\s*([^<]+?)\s*<\/xbrldi:explicitMember>\s*<\/xbrli:segment>/i;

//     const match = userAnswer.match(regex);

//     if (!match) {
//       // If the primary regex doesn't match, provide a more generic error
//       // or try to identify if just the member element is missing.
//       // For this problem, "Missing explicitMember" is a good first step.
//       return { isCorrect: false, error: "❌ Missing <xbrldi:explicitMember> in <xbrli:segment> or incorrect structure." };
//     }

//     const dimensionAttr = match[1]; // Value from the first capturing group
//     const memberText = match[2].trim(); // Value from the second capturing group, trimmed

//     const correctDimension = "ex:ProductAxis";
//     const validMembers = ["ex:CarsMember", "ex:BikesMember"];

//     if (dimensionAttr !== correctDimension) {
//       return { isCorrect: false, error: `❌ Dimension attribute should be "${correctDimension}". Found "${dimensionAttr}".` };
//     }
//     if (!validMembers.includes(memberText)) {
//       return { isCorrect: false, error: `❌ Member should be one of ${validMembers.join(", ")}. Found "${memberText}".` };
//     }

//     return { isCorrect: true, error: "✅ Correct! You successfully added the dimension." };

//   } catch (error) {
//     console.error("Validation error:", error);
//     return { isCorrect: false, error: "An unexpected error occurred during validation." };
//   }
// }

function validateBeginner1(instanceXmlString) {
  try {
    const parser = new DOMParser();
    const xmlDoc = parser.parseFromString(instanceXmlString, "application/xml");
    console.log("i am here ");

    const errors = xmlDoc.getElementsByTagName("parsererror");
    if (errors.length > 0) {
      return { isCorrect: false, error: "❌ Invalid XML structure." };
    }

    const nsResolver = (prefix) => {
      const ns = {
        xbrli: "http://www.xbrl.org/2003/instance",
        xbrldi: "http://xbrl.org/2006/xbrldi",
        ex: "http://example.com/taxonomy"
      };
      return ns[prefix] || null;
    };

    const explicitMember = xmlDoc.evaluate(
      "//xbrli:context[@id='Context_A']/xbrli:entity/xbrli:segment/xbrldi:explicitMember",
      xmlDoc,
      nsResolver,
      XPathResult.FIRST_ORDERED_NODE_TYPE,
      null
    ).singleNodeValue;

    if (!explicitMember) {
      return {
        isCorrect: false,
        error: "❌ Missing `<xbrldi:explicitMember>` element inside `<xbrli:segment>`."
      };
    }

    const dimensionAttr = explicitMember.getAttribute("dimension");
    console.log(dimensionAttr);
    const memberValue = explicitMember.textContent.trim();
    console.log(memberValue);

    const validDimension = dimensionAttr === "ex:ProductAxis";
    const validMember = ["ex:CarsMember", "ex:BikesMember"].includes(memberValue);

    if (!validDimension) {
      return { isCorrect: false, error: "❌ The dimension must be `ex:ProductAxis`." };
    }

    if (!validMember) {
      return {
        isCorrect: false,
        error: "❌ Member must be either `ex:CarsMember` or `ex:BikesMember`."
      };
    }

    return { isCorrect: true, error: "✅ Correct! The dimension and member are properly used." };
  } catch (e) {
    return { isCorrect: false, error: `❌ Error validating XML: ${e.message}` };
  }
}


function validateBeginner2(instanceXmlString) {
  try {
    const parser = new DOMParser();
    const xmlDoc = parser.parseFromString(instanceXmlString, "application/xml");

    const errors = xmlDoc.getElementsByTagName("parsererror");
    if (errors.length > 0) {
      return { isCorrect: false, error: "❌ Invalid XML structure." };
    }

    const nsResolver = (prefix) => {
      const ns = {
        xbrli: "http://www.xbrl.org/2003/instance",
        xbrldi: "http://xbrl.org/2006/xbrldi",
        ex: "http://example.com/taxonomy"
      };
      return ns[prefix] || null;
    };

    const explicitMember = xmlDoc.evaluate(
      "//xbrli:context[@id='Context_B']/xbrli:entity/xbrli:segment/xbrldi:explicitMember",
      xmlDoc,
      nsResolver,
      XPathResult.FIRST_ORDERED_NODE_TYPE,
      null
    ).singleNodeValue;

    if (!explicitMember) {
      return {
        isCorrect: false,
        error: "❌ Missing `<xbrldi:explicitMember>` inside `<xbrli:segment>` in Context_B."
      };
    }

    const dimensionAttr = explicitMember.getAttribute("dimension");
    const memberValue = explicitMember.textContent.trim();

    const validDimension = dimensionAttr === "ex:LocationAxis";
    const validMember = ["ex:NorthMember", "ex:SouthMember"].includes(memberValue);

    if (!validDimension) {
      return {
        isCorrect: false,
        error: `❌ Dimension is "${dimensionAttr}", but should be "ex:LocationAxis".`
      };
    }

    if (!validMember) {
      return {
        isCorrect: false,
        error: `❌ Member is "${memberValue}", but must be "ex:NorthMember" or "ex:SouthMember".`
      };
    }

    return {
      isCorrect: true,
      error: "✅ Correct! The dimension and member are spelled correctly and match the taxonomy."
    };

  } catch (e) {
    return {
      isCorrect: false,
      error: `❌ Error validating XML: ${e.message}`
    };
  }
}


function validateIntermediate1(userInput) {
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(userInput, "application/xml");

  const errors = xmlDoc.getElementsByTagName("parsererror");
  if (errors.length > 0) {
    return {
      isCorrect: false,
      error: "❌ Invalid XML format. Please ensure your syntax is correct."
    };
  }

  const nsResolver = (prefix) => {
    const ns = {
      xbrli: "http://www.xbrl.org/2003/instance",
      xbrldi: "http://xbrl.org/2006/xbrldi",
      ex: "http://example.com/taxonomy"
    };
    return ns[prefix] || null;
  };

  const explicitMember = xmlDoc.evaluate(
    "//xbrli:context/xbrli:entity/xbrli:segment/xbrldi:explicitMember",
    xmlDoc,
    nsResolver,
    XPathResult.FIRST_ORDERED_NODE_TYPE,
    null
  ).singleNodeValue;

  console.log(explicitMember)
  if (!explicitMember) {
    return {
      isCorrect: false,
      error: "❌ No <xbrldi:explicitMember> element found. Please include one."
    };
  }

  const dimensionAttr = explicitMember.getAttribute("dimension");
  const validMembers = ["ex:AsiaMember", "ex:EuropeMember"];

  if (dimensionAttr !== "ex:RegionAxis") {
    return {
      isCorrect: false,
      error: `❌ Incorrect dimension: "${dimensionAttr}". It should be "ex:RegionAxis".`
    };
  }

  const memberValue = explicitMember.textContent.trim();
   console.log(memberValue)
  if (!validMembers.includes(memberValue)) {
    return {
      isCorrect: false,
      error: `❌ Invalid member: "${memberValue}". Use "ex:AsiaMember" or "ex:EuropeMember".`
    };
  }

  return {
    isCorrect: true,
    error: "✅ Correct! You have fixed both the dimension and the member name."
  };
}

function validateIntermediate2(userInput) {
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(userInput, "application/xml");

  const errors = xmlDoc.getElementsByTagName("parsererror");
  if (errors.length > 0) {
    return {
      isCorrect: false,
      error: "❌ Invalid XML format. Please ensure your syntax is correct."
    };
  }

  const nsResolver = (prefix) => {
    const ns = {
      xbrli: "http://www.xbrl.org/2003/instance",
      xbrldi: "http://xbrl.org/2006/xbrldi",
      ex: "http://example.com/taxonomy"
    };
    return ns[prefix] || null;
  };

  const typedMember = xmlDoc.evaluate(
    "//xbrli:context/xbrli:entity/xbrli:segment/xbrldi:typedMember",
    xmlDoc,
    nsResolver,
    XPathResult.FIRST_ORDERED_NODE_TYPE,
    null
  ).singleNodeValue;

  if (!typedMember) {
    return {
      isCorrect: false,
      error: "❌ Missing <xbrldi:typedMember> inside <xbrli:segment>. Please add it."
    };
  }

  const dimensionAttr = typedMember.getAttribute("dimension");
  if (dimensionAttr !== "ex:ProductAxis") {
    return {
      isCorrect: false,
      error: `❌ Incorrect dimension: "${dimensionAttr}". It should be "ex:ProductAxis".`
    };
  }

  const productNode = xmlDoc.evaluate(
    "ex:product",
    typedMember,
    nsResolver,
    XPathResult.FIRST_ORDERED_NODE_TYPE,
    null
  ).singleNodeValue;

  if (!productNode) {
    return {
      isCorrect: false,
      error: "❌ Missing <ex:product> element inside <xbrldi:typedMember>."
    };
  }

  if (!productNode.textContent.trim()) {
    return {
      isCorrect: false,
      error: "❌ <ex:product> should not be empty. Please provide a product value."
    };
  }

  return {
    isCorrect: true,
    error: "✅ Well done! Your typed dimension is correctly defined."
  };
}




function validateAdvanced1(userInput) {
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(userInput, "application/xml");

  const errors = xmlDoc.getElementsByTagName("parsererror");
  if (errors.length > 0) {
    return {
      isCorrect: false,
      error: "❌ Invalid XML format. Please ensure your syntax is correct."
    };
  }

  const nsResolver = (prefix) => {
    const ns = {
      xbrli: "http://www.xbrl.org/2003/instance",
      xbrldi: "http://xbrl.org/2006/xbrldi",
      ex: "http://example.com/taxonomy"
    };
    return ns[prefix] || null;
  };

  const getExplicitMembers = (location) => {
    const snapshot = xmlDoc.evaluate(
      `//xbrli:context/xbrli:entity/xbrli:${location}/xbrldi:explicitMember`,
      xmlDoc,
      nsResolver,
      XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,
      null
    );

    const members = [];
    for (let i = 0; i < snapshot.snapshotLength; i++) {
      members.push(snapshot.snapshotItem(i));
    }
    return members;
  };

  const segmentMembers = getExplicitMembers("segment");
  const scenarioMembers = getExplicitMembers("scenario");

  const seenDimensions = new Set();

  const validDimensions = new Set(["ex:RegionAxis", "ex:ProductAxis"]);
  const validMembers = new Set([
    "ex:AsiaMember",
    "ex:EuropeMember",
    "ex:ElectronicsMember",
    "ex:FurnitureMember"
  ]);

  const allMembers = [...segmentMembers, ...scenarioMembers];
  for (const member of allMembers) {
    const dim = member.getAttribute("dimension");
    const val = member.textContent.trim();

    if (!validDimensions.has(dim)) {
      return {
        isCorrect: false,
        error: `❌ Invalid dimension "${dim}". Only dimensions defined in the taxonomy can be used.`
      };
    }

    if (!validMembers.has(val)) {
      return {
        isCorrect: false,
        error: `❌ Invalid member "${val}". Only members defined in the taxonomy can be used.`
      };
    }

    if (seenDimensions.has(dim)) {
      return {
        isCorrect: false,
        error: `❌ Dimension "${dim}" is used more than once. A dimension axis must appear only once in a context.`
      };
    }

    seenDimensions.add(dim);
  }

  // ✅ Correct placement checks
  const regionInSegment = segmentMembers.find(
    (m) => m.getAttribute("dimension") === "ex:RegionAxis"
  );
  const regionInScenario = scenarioMembers.find(
    (m) => m.getAttribute("dimension") === "ex:RegionAxis"
  );
  const productInSegment = segmentMembers.find(
    (m) => m.getAttribute("dimension") === "ex:ProductAxis"
  );
  const productInScenario = scenarioMembers.find(
    (m) => m.getAttribute("dimension") === "ex:ProductAxis"
  );

  if (!regionInSegment) {
    return {
      isCorrect: false,
      error: "❌ <ex:RegionAxis> must be defined in <xbrli:segment>."
    };
  }

  if (regionInScenario) {
    return {
      isCorrect: false,
      error:
        "❌ Duplicate <ex:RegionAxis> found in <xbrli:scenario>. It must only appear once, preferably in <xbrli:segment>."
    };
  }

  if (!productInScenario) {
    return {
      isCorrect: false,
      error:
        "❌ <ex:ProductAxis> must be placed in <xbrli:scenario>, but it was not found there."
    };
  }

  if (productInSegment) {
    return {
      isCorrect: false,
      error:
        "❌ <ex:ProductAxis> should not appear in <xbrli:segment>. Move it to <xbrli:scenario>."
    };
  }

  return {
    isCorrect: true,
    error: "✅ Great job! Your dimensions are uniquely and correctly placed."
  };
}

// --- Validator for Activity 1: Create the Label Resource ---
function validateLabelPart1(userInput) {
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(userInput, "application/xml");
console.log(xmlDoc)
  const errors = xmlDoc.getElementsByTagName("parsererror");
  console.log(errors)
  if (errors.length > 0) {
    return {
      isCorrect: false,
      error: "❌ Invalid XML format. Please ensure your syntax is correct."
    };
  }

  const label = xmlDoc.getElementsByTagName("link:label")[0];
  if (!label) {
    return {
      isCorrect: false,
      error: "❌ Missing <link:label> element."
    };
  }

  const xlinkLabel = label.getAttribute("xlink:label");
  const xlinkType = label.getAttribute("xlink:type");
  const xlinkRole = label.getAttribute("xlink:role");
  const textContent = label.textContent.trim();

  if (!xlinkLabel) {
    return {
      isCorrect: false,
      error: "❌ <link:label> must have an xlink:label attribute."
    };
  }

  if (xlinkType !== "resource") {
    return {
      isCorrect: false,
      error: "❌ <link:label> must have xlink:type=\"resource\"."
    };
  }

  if (xlinkRole !== "http://www.xbrl.org/2003/role/terseLabel") {
    return {
      isCorrect: false,
      error: "❌ xlink:role must be set to the URI for a terse label."
    };
  }

  if (textContent !== "Revenue") {
    return {
      isCorrect: false,
      error: `❌ The label text must be "Revenue", but got "${textContent}".`
    };
  }

  return {
    isCorrect: true,
    error: "✅ Great job! You've correctly defined the terse label."
  };
}



// --- Validator for Activity 2: Connect the Label ---
function validateLabelPart2(userInput) {
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(userInput, "application/xml");

  const errors = xmlDoc.getElementsByTagName("parsererror");
  console.log(errors)
  if (errors.length > 0) {
    return {
      isCorrect: false,
      error: "❌ Invalid XML format. Please ensure your syntax is correct."
    };
  }

  const arc = xmlDoc.getElementsByTagName("link:labelArc")[0];
  if (!arc) {
    return {
      isCorrect: false,
      error: "❌ Missing <link:labelArc> element."
    };
  }

  const from = arc.getAttribute("xlink:from");
  const to = arc.getAttribute("xlink:to");
  const arcrole = arc.getAttribute("xlink:arcrole");
  const xlinkType = arc.getAttribute("xlink:type");

  if (from !== "loc_revenue") {
    return {
      isCorrect: false,
      error: `❌ xlink:from must be "loc_revenue", but got "${from}".`
    };
  }

  if (to !== "lab_revenue_terse") {
    return {
      isCorrect: false,
      error: `❌ xlink:to must be "lab_revenue_terse", but got "${to}".`
    };
  }

  if (arcrole !== "http://www.xbrl.org/2003/arcrole/concept-label") {
    return {
      isCorrect: false,
      error: "❌ xlink:arcrole must be set to the standard concept-label arcrole URI."
    };
  }

  if (xlinkType !== "arc") {
    return {
      isCorrect: false,
      error: "❌ xlink:type must be set to \"arc\"."
    };
  }

  return {
    isCorrect: true,
    error: "✅ Well done! The <link:labelArc> connects your concept and label correctly."
  };
}


function validatePresentationPart1(userInput) {
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(userInput, "application/xml");

  const errors = xmlDoc.getElementsByTagName("parsererror");
  if (errors.length > 0) {
    return {
      isCorrect: false,
      error: "❌ Invalid XML format. Please ensure your syntax is correct."
    };
  }

  const arc = xmlDoc.getElementsByTagName("link:presentationArc")[0];
  if (!arc) {
    return {
      isCorrect: false,
      error: "❌ Missing <link:presentationArc> element."
    };
  }

  const from = arc.getAttribute("xlink:from");
  const to = arc.getAttribute("xlink:to");
  const arcrole = arc.getAttribute("xlink:arcrole");
  const xlinkType = arc.getAttribute("xlink:type");
  const order = arc.getAttribute("order");

  if (from !== "loc_TotalOperatingExpenses") {
    return {
      isCorrect: false,
      error: `❌ xlink:from must be "loc_TotalOperatingExpenses", but got "${from}".`
    };
  }

  if (to !== "loc_SalariesAndWages") {
    return {
      isCorrect: false,
      error: `❌ xlink:to must be "loc_SalariesAndWages", but got "${to}".`
    };
  }

  if (arcrole !== "http://www.xbrl.org/2003/arcrole/parent-child") {
    return {
      isCorrect: false,
      error: "❌ xlink:arcrole must be set to the standard parent-child arcrole URI."
    };
  }

  if (xlinkType !== "arc") {
    return {
      isCorrect: false,
      error: "❌ xlink:type must be set to \"arc\"."
    };
  }

  if (order !== "10") {
    return {
      isCorrect: false,
      error: `❌ order must be "10", but got "${order}".`
    };
  }

  return {
    isCorrect: true,
    error: "✅ Well done! The <link:presentationArc> correctly links the parent and child concepts."
  };
}


function validatePresentationPart2(userInput) {
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(userInput, "application/xml");

  const errors = xmlDoc.getElementsByTagName("parsererror");
  if (errors.length > 0) {
    return {
      isCorrect: false,
      error: "❌ Invalid XML format. Please ensure your syntax is correct and well-formed."
    };
  }

  const nsResolver = (prefix) => {
    const ns = {
      link: "http://www.xbrl.org/2003/linkbase",
      xlink: "http://www.w3.org/1999/xlink",
      ex: "http://example.com/taxonomy"
    };
    return ns[prefix] || null;
  };

  // 1. Validate the pre-existing SalariesAndWages arc (from Activity 1)
  const salariesArcSnapshot = xmlDoc.evaluate(
    `//link:presentationArc[@xlink:from='loc_TotalOperatingExpenses' and @xlink:to='loc_SalariesAndWages' and @xlink:arcrole='http://www.xbrl.org/2003/arcrole/parent-child' and @xlink:type='arc' and @order='10']`,
    xmlDoc,
    nsResolver,
    XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,
    null
  );

  if (salariesArcSnapshot.snapshotLength !== 1) {
    return {
      isCorrect: false,
      error: "❌ The arc for 'SalariesAndWages' (from the previous activity) is missing or incorrect. Please ensure it's present exactly as expected: `xlink:from=\"loc_TotalOperatingExpenses\" xlink:to=\"loc_SalariesAndWages\" xlink:arcrole=\"http://www.xbrl.org/2003/arcrole/parent-child\" xlink:type=\"arc\" order=\"10\"`."
    };
  }

  // 2. Find all presentation arcs in the document
  const allArcsSnapshot = xmlDoc.evaluate(
    "//link:presentationArc",
    xmlDoc,
    nsResolver,
    XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,
    null
  );

  // We expect exactly two arcs in total for this activity (SalariesAndWages + RentExpense)
  if (allArcsSnapshot.snapshotLength !== 2) {
    return {
      isCorrect: false,
      error: `❌ Incorrect number of <link:presentationArc> elements found (${allArcsSnapshot.snapshotLength}). You should have exactly two arcs: one for SalariesAndWages (already provided) and one for RentExpense.`
    };
  }

  // 3. Identify and validate the new RentExpense arc
  let rentArcFound = null;
  for (let i = 0; i < allArcsSnapshot.snapshotLength; i++) {
    const arc = allArcsSnapshot.snapshotItem(i);
    const from = arc.getAttributeNS(nsResolver('xlink'), 'from');
    const to = arc.getAttributeNS(nsResolver('xlink'), 'to');

    // Check if this is the RentExpense arc (not the SalariesAndWages one)
    if (from === "loc_TotalOperatingExpenses" && to === "loc_RentExpense") {
      rentArcFound = arc;
      break; // Found it
    }
  }

  if (!rentArcFound) {
    return {
      isCorrect: false,
      error: "❌ The <link:presentationArc> for 'RentExpense' is missing or its 'xlink:from' or 'xlink:to' attributes are incorrect. Please add it and ensure it links `loc_TotalOperatingExpenses` to `loc_RentExpense`."
    };
  }

  // 4. Validate the attributes of the RentExpense arc
  const rentArcFrom = rentArcFound.getAttributeNS(nsResolver('xlink'), 'from');
  const rentArcTo = rentArcFound.getAttributeNS(nsResolver('xlink'), 'to');
  const rentArcArcrole = rentArcFound.getAttributeNS(nsResolver('xlink'), 'arcrole');
  const rentArcType = rentArcFound.getAttributeNS(nsResolver('xlink'), 'type');
  const rentArcOrderAttr = rentArcFound.getAttribute('order'); // Get as string first

  if (rentArcFrom !== "loc_TotalOperatingExpenses") {
    return {
      isCorrect: false,
      error: "❌ The 'xlink:from' attribute for 'RentExpense' arc must be 'loc_TotalOperatingExpenses'."
    };
  }
  if (rentArcTo !== "loc_RentExpense") {
    return {
      isCorrect: false,
      error: "❌ The 'xlink:to' attribute for 'RentExpense' arc must be 'loc_RentExpense'."
    };
  }
  if (rentArcArcrole !== "http://www.xbrl.org/2003/arcrole/parent-child") {
    return {
      isCorrect: false,
      error: "❌ The 'xlink:arcrole' attribute for 'RentExpense' arc must be 'http://www.xbrl.org/2003/arcrole/parent-child'."
    };
  }
  if (rentArcType !== "arc") {
    return {
      isCorrect: false,
      error: "❌ The 'xlink:type' attribute for 'RentExpense' arc must be 'arc'."
    };
  }

  // Validate 'order' attribute
  const rentArcOrder = parseFloat(rentArcOrderAttr);
  if (isNaN(rentArcOrder) || rentArcOrderAttr.trim() === '') {
      return {
          isCorrect: false,
          error: "❌ The 'order' attribute for 'RentExpense' is missing or not a valid number. It must be a numeric value."
      };
  }
  if (rentArcOrder <= 10) {
    return {
      isCorrect: false,
      error: `❌ The 'order' attribute for 'RentExpense' (${rentArcOrder}) must be a number *greater than* 10 to ensure it appears after SalariesAndWages.`
    };
  }

  // All checks passed
  return {
    isCorrect: true,
    error: "✅ Fantastic! You have successfully added 'RentExpense' and correctly ordered it under 'TotalOperatingExpenses'."
  };
}


function validateCalculationPart1(userInput) {
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(userInput, "application/xml");

  const errors = xmlDoc.getElementsByTagName("parsererror");
  if (errors.length > 0) {
    return {
      isCorrect: false,
      error: "❌ Invalid XML format. Please ensure your syntax is correct."
    };
  }

  const arcs = xmlDoc.getElementsByTagName("link:calculationArc");
  if (arcs.length === 0) {
    return {
      isCorrect: false,
      error: "❌ Missing <link:calculationArc> element."
    };
  }

  const arc = arcs[0];

  const from = arc.getAttribute("xlink:from");
  const to = arc.getAttribute("xlink:to");
  const arcrole = arc.getAttribute("xlink:arcrole");
  const xlinkType = arc.getAttribute("xlink:type");
  const weight = arc.getAttribute("weight");

  if (!from || from.includes("[") || from !== "loc_NetIncome") {
    return {
      isCorrect: false,
      error: `❌ xlink:from must be "loc_NetIncome" (no placeholders or typos).`
    };
  }

  if (!to || to.includes("[") || to !== "loc_Revenue") {
    return {
      isCorrect: false,
      error: `❌ xlink:to must be "loc_Revenue" (no placeholders or typos).`
    };
  }

  if (!arcrole || arcrole.includes("[") || arcrole !== "http://www.xbrl.org/2003/arcrole/summation-item") {
    return {
      isCorrect: false,
      error: "❌ xlink:arcrole must be exactly 'http://www.xbrl.org/2003/arcrole/summation-item'."
    };
  }

  if (xlinkType !== "arc") {
    return {
      isCorrect: false,
      error: "❌ xlink:type must be set to \"arc\"."
    };
  }

  if (weight !== "1") {
    return {
      isCorrect: false,
      error: `❌ weight must be "1", but got "${weight}".`
    };
  }

  return {
    isCorrect: true,
    error: "✅ Great job! Your <link:calculationArc> correctly links NetIncome to Revenue with weight 1."
  };
}



function validateCalculationPart2(userInput) {
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(userInput, "application/xml");

  const errors = xmlDoc.getElementsByTagName("parsererror");
  if (errors.length > 0) {
    return {
      isCorrect: false,
      error: "❌ Invalid XML format. Please ensure your syntax is correct."
    };
  }

  const arcs = Array.from(xmlDoc.getElementsByTagName("link:calculationArc"));

  if (arcs.length < 2) {
    return {
      isCorrect: false,
      error: "❌ It looks like you're missing the second <link:calculationArc> element for CostOfGoodsSold."
    };
  }

  // Look for the arc with loc_CostOfGoodsSold and weight -1
  const secondArc = arcs.find(arc =>
    arc.getAttribute("xlink:from") === "loc_NetIncome" &&
    arc.getAttribute("xlink:to") === "loc_CostOfGoodsSold" &&
    arc.getAttribute("xlink:arcrole") === "http://www.xbrl.org/2003/arcrole/summation-item" &&
    arc.getAttribute("xlink:type") === "arc" &&
    arc.getAttribute("weight") === "-1"
  );

  if (!secondArc) {
    return {
      isCorrect: false,
      error: "❌ Your second <link:calculationArc> must link from 'loc_NetIncome' to 'loc_CostOfGoodsSold' with weight=\"-1\"."
    };
  }

  return {
    isCorrect: true,
    error: "✅ Well done! You've correctly added the subtraction arc for CostOfGoodsSold."
  };
}

function validateDefinitionDomainMember(userInput) {
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(userInput, "application/xml");

  const errors = xmlDoc.getElementsByTagName("parsererror");
  if (errors.length > 0) {
    return {
      isCorrect: false,
      error: "❌ Invalid XML syntax. Please check for missing brackets or quotes."
    };
  }

  const arcs = Array.from(xmlDoc.getElementsByTagName("link:definitionArc"));

  if (arcs.length === 0) {
    return {
      isCorrect: false,
      error: "❌ You need to add a <link:definitionArc> element to connect the axis to its member."
    };
  }

  const arc = arcs.find(el =>
    el.getAttribute("xlink:from") === "loc_GeoRegionAxis" &&
    el.getAttribute("xlink:to") === "loc_EuropeMember" &&
    el.getAttribute("xlink:arcrole") === "http://xbrl.org/2005/arcrole/domain-member" &&
    el.getAttribute("xlink:type") === "arc"
  );

  if (!arc) {
    return {
      isCorrect: false,
      error: "❌ Your <link:definitionArc> must link from 'loc_GeoRegionAxis' to 'loc_EuropeMember' with the correct arcrole and type."
    };
  }

  return {
    isCorrect: true,
    error: "✅ Great job! You correctly defined the domain-member relationship."
  };
}

module.exports = {
  validateUnitRefAnswer,
  validateContextRefAnswer,
  validateDateRangeAnswer,
  validateCurrencyCodeAnswer,
  validateRevenueValueAnswer,
  validateAllFixesAnswer,
  validateBushchatHandsOnSnippet,
  validateDimensionUsage,
  validateCalculation,
  validateDimensionAndCalculation,
  validateBeginner1,
  validateBeginner2,
  validateIntermediate1,
  validateIntermediate2,
  validateAdvanced1,
  validateLabelPart1,
  validateLabelPart2,
  validatePresentationPart1,
  validatePresentationPart2,
  validateCalculationPart1,
  validateCalculationPart2,
  validateDefinitionDomainMember,
};
